-------------------------------------------------------------------------------
Test set: io.apicurio.tests.serdes.apicurio.AvroSerdeIT
-------------------------------------------------------------------------------
Tests run: 21, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 109.5 s <<< FAILURE! -- in io.apicurio.tests.serdes.apicurio.AvroSerdeIT
io.apicurio.tests.serdes.apicurio.AvroSerdeIT.testSimpleTopicIdStrategyFindLatest -- Time elapsed: 4.616 s <<< ERROR!
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition topic-34ca2bed_779e_4e26_83e0_e58fa274be0c-0 at offset 0. If needed, please seek past the record to continue consumption.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.consumeMessages(KafkaSerdesTester.java:207)
	at io.apicurio.tests.serdes.apicurio.SimpleSerdesTesterBuilder$SimpleSerdesTester.test(SimpleSerdesTesterBuilder.java:156)
	at io.apicurio.tests.serdes.apicurio.AvroSerdeIT.testSimpleTopicIdStrategyFindLatest(AvroSerdeIT.java:106)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition topic-34ca2bed_779e_4e26_83e0_e58fa274be0c-0 at offset 0. If needed, please seek past the record to continue consumption.
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.newRecordDeserializationException(CompletedFetch.java:346)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:330)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:284)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.fetchRecords(FetchCollector.java:169)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.collectFetch(FetchCollector.java:135)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:146)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.pollForFetches(ClassicKafkaConsumer.java:699)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:623)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.lambda$consumeMessages$5(KafkaSerdesTester.java:179)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:242)
	at io.apicurio.registry.resolver.cache.ERCache.getValue(ERCache.java:173)
	at io.apicurio.registry.resolver.cache.ERCache.getByContentId(ERCache.java:152)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByContentId(DefaultSchemaResolver.java:197)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:171)
	at io.apicurio.registry.serde.AbstractDeserializer.resolve(AbstractDeserializer.java:104)
	at io.apicurio.registry.serde.AbstractDeserializer.deserializeData(AbstractDeserializer.java:82)
	at io.apicurio.registry.serde.KafkaDeserializer.deserialize(KafkaDeserializer.java:33)
	at io.apicurio.registry.serde.KafkaDeserializer.deserialize(KafkaDeserializer.java:50)
	at io.apicurio.registry.serde.avro.AvroKafkaDeserializer.deserialize(AvroKafkaDeserializer.java:57)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:81)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:327)
	... 11 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:437)
	at io.kiota.http.vertx.VertXRequestAdapter.sendCollection(VertXRequestAdapter.java:130)
	at io.apicurio.registry.rest.client.ids.contentids.item.references.ReferencesRequestBuilder.get(ReferencesRequestBuilder.java:53)
	at io.apicurio.registry.rest.client.ids.contentids.item.references.ReferencesRequestBuilder.get(ReferencesRequestBuilder.java:43)
	at io.apicurio.registry.resolver.client.RegistryClientFacadeImpl.getReferencesByContentId(RegistryClientFacadeImpl.java:48)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.lambda$resolveSchemaByContentId$1(DefaultSchemaResolver.java:205)
	at io.apicurio.registry.resolver.cache.ERCache.lambda$getValue$0(ERCache.java:174)
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:227)
	... 22 more
Caused by: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:431)
	... 29 more
Caused by: io.vertx.core.http.HttpClosedException: Connection was closed

