-------------------------------------------------------------------------------
Test set: io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
-------------------------------------------------------------------------------
Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 61.70 s <<< FAILURE! -- in io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testFindLatestAndUseBody -- Time elapsed: 6.119 s <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'registry-app-ksql043.apps.ci419.apicurio-testing.org' [A(1)] and search domain query for configured domains failed as well: [sbo4f4120sjejcpudlippbucbf.ex.internal.cloudapp.net]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.produceMessages(KafkaSerdesTester.java:160)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.produceMessages(KafkaSerdesTester.java:123)
	at io.apicurio.tests.serdes.apicurio.SimpleSerdesTesterBuilder$SimpleSerdesTester.test(SimpleSerdesTesterBuilder.java:139)
	at io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testFindLatestAndUseBody(ProtobufSerdeIT.java:466)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'registry-app-ksql043.apps.ci419.apicurio-testing.org' [A(1)] and search domain query for configured domains failed as well: [sbo4f4120sjejcpudlippbucbf.ex.internal.cloudapp.net]
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:242)
	at io.apicurio.registry.resolver.cache.ERCache.getValue(ERCache.java:173)
	at io.apicurio.registry.resolver.cache.ERCache.getByArtifactCoordinates(ERCache.java:158)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReferenceCached(DefaultSchemaResolver.java:338)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByCoordinates(DefaultSchemaResolver.java:193)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.getSchemaFromRegistry(DefaultSchemaResolver.java:130)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.lambda$resolveSchema$0(DefaultSchemaResolver.java:84)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchema(DefaultSchemaResolver.java:84)
	at io.apicurio.registry.serde.AbstractSerializer.serializeData(AbstractSerializer.java:62)
	at io.apicurio.registry.serde.KafkaSerializer.serialize(KafkaSerializer.java:77)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:1046)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:993)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:875)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.lambda$produceMessages$3(KafkaSerdesTester.java:138)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'registry-app-ksql043.apps.ci419.apicurio-testing.org' [A(1)] and search domain query for configured domains failed as well: [sbo4f4120sjejcpudlippbucbf.ex.internal.cloudapp.net]
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:437)
	at io.kiota.http.vertx.VertXRequestAdapter.send(VertXRequestAdapter.java:167)
	at io.apicurio.registry.rest.client.groups.item.artifacts.item.versions.item.WithVersionExpressionItemRequestBuilder.get(WithVersionExpressionItemRequestBuilder.java:128)
	at io.apicurio.registry.rest.client.groups.item.artifacts.item.versions.item.WithVersionExpressionItemRequestBuilder.get(WithVersionExpressionItemRequestBuilder.java:111)
	at io.apicurio.registry.resolver.client.RegistryClientFacadeImpl.getVersionCoordinatesByGAV(RegistryClientFacadeImpl.java:159)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveByCoordinates(DefaultSchemaResolver.java:352)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.lambda$resolveSchemaByArtifactReferenceCached$6(DefaultSchemaResolver.java:340)
	at io.apicurio.registry.resolver.cache.ERCache.lambda$getValue$0(ERCache.java:174)
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:227)
	... 16 more
Caused by: java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'registry-app-ksql043.apps.ci419.apicurio-testing.org' [A(1)] and search domain query for configured domains failed as well: [sbo4f4120sjejcpudlippbucbf.ex.internal.cloudapp.net]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:431)
	... 24 more
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'registry-app-ksql043.apps.ci419.apicurio-testing.org' [A(1)] and search domain query for configured domains failed as well: [sbo4f4120sjejcpudlippbucbf.ex.internal.cloudapp.net]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:455)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:70)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:524)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:572)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:649)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:642)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:131)
	at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:343)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:278)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [6438: /127.0.0.53:53] DefaultDnsQuestion(registry-app-ksql043.apps.ci419.apicurio-testing.org. IN A) query '6438' via UDP timed out after 5000 milliseconds (no stack trace available)

